# 基本配置
bark_id: ''  # bark app通知id
duration: 120  # 执行间隔时间秒
history_msg_length: 50  # 历史消息长度
location_name: ''  # get_address_id时候用来过滤出指定的地址，如默认地址是：上海市黄浦区人民大道185号人民广场，就填写人民广场

# 抓包后要填写的参数
station_id: ''  # 抓包后的站点id
longitude: ''  # ddmc-longitude 上海的经度
latitude: ''  # ddmc-latitude 上海的纬度
city_number: '0101'  # ddmc-city-number 0101上海
api_version: '9.49.2'  # ddmc-api-version
build_version: '2.82.0'    # ddmc-build-version
ua: ''
cookie: ''  # 账号cookie 类似:DDXQSESSID=XXXXX
device_id: ''  # ddmc-device-id
uid: ''  # ddmc-uid
device_token: '' # 从raw_body里面找到
raw_body: ''  # 可以不用填

# 其它
name_of_all_categories: [
    "预制菜", "蔬菜豆制品", "肉禽蛋", "水产海鲜", "水果鲜花", "叮咚特供", "乳品烘焙", "速食冻品", "粮油调味", "酒水饮料", "火锅到家", "熟食卤味",
    "休闲零食", "日用百货", "方便食品", "营养早餐", "宝妈严选", "轻养星球", "在家烧烤", "云仓快送"
]
name_of_categories_i_care: [
    '酒水饮料'
]
